### ISSUE TITLE
The getfider.com display as broken when third-party sources blocked

### ISSUE THREAD

**Issue by Aikatsui** [getfider/getfider.com#15]
Can you please remove them from https://getfider.com/? it seems to me really not necessary

![image](https://user-images.githubusercontent.com/63988538/110065802-9bfaa200-7da2-11eb-8c84-997f7957a0bb.png)

**Comment by goenning** [comment]
is that blocking cdnjs and fontawesome?

**Comment by Aikatsui** [comment]
Yes both, as i mentioned above i don't think those're more important to your site
sometimes we can try to mitigate such issues using https://codeberg.org/nobody/LocalCDN but not perfect much

**Comment by goenning** [comment]
Should be ok now
